/**
 * Configuration version of all build dependencies
 */
object BuildDependenciesVersions {
    const val KOTLIN = "1.3.72"
    const val APPCOMPAT = "1.1.0"
    const val MATERIAL = "1.1.0"
    const val COROUTINES = "1.3.5"
    const val ROOM = "2.2.5"
    const val RECYCLER_VIEW = "1.1.0"
    const val NAVIGATION = "2.2.2"
    const val LIFECYCLE = "2.2.0"
    const val CORE_KTX = "1.2.0"
    const val FRAGMENT_KTX = "1.2.4"
    const val CONSTRAINT_LAYOUT = "1.1.3"
    const val SWIPE_REFRESH_LAYOUT = "1.0.0"
    const val PAGING = "2.1.2"
    const val DAGGER = "2.27"
    const val TIMBER = "4.7.1"
    const val RETROFIT = "2.8.1"
    const val LOGGING = "4.6.0"
    const val MOSHI = "1.9.2"
    const val COIL = "0.10.1"
    const val PLAY_CORE = "1.7.2"
    const val LEAKCANARY = "2.2"
    const val DATABINDING = "3.1.4"
    const val AUTO_SERVICE = "1.0-rc4"
    const val FIREBASE_ANALYTICS = "17.4.0"
    const val FIREBASE_FIRESTORE = "21.4.3"
    const val FIREBASE_AUTH = "19.3.1"
    const val COROUTINES_PLAY_SERVICES = "1.3.5"

    // Tests
    const val TEST = "1.2.0"
    const val EXT = "1.1.1"
    const val ARCH_CORE = "2.1.0"
    const val JUNIT = "4.13"
    const val ROBOELECTRIC = "4.3.1"
    const val MOCKITO = "2.2.0"
    const val MOCKK = "1.10.0"
    const val ASSERTJ = "3.15.0"
    const val ESPRESSO = "3.2.0"
    const val FRAGMENT_TEST = "1.2.4"
    const val MOCK_WEB_SERVER = "4.6.0"
}
